apiVersion: v2
name: ndb-operator-test
description: A Helm chart for Nutanix Database Kubernetes Operator
type: application
version: 0.5.3-test
appVersion: v0.5.1
maintainers:
  - name: Shivaprasad M B
    email: shivaprasad.mb@nutanix.com
annotations:
  artifacthub.io/changes: |
    - kind: fixed
      description: "Upgraded internal dependencies."
    - kind: security
      description: "Upgraded kube-rbac-proxy from v0.15.0 to v0.16.0."
    - kind: added
      description: "test release for security analysis"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/maintainers: |
    - name: Shivaprasad M B
      email: shivaprasad.mb@nutanix.com
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "false"
